# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
    - master
pr:
  - master
variables:
  - name: versionWheels
    value: '0.6'
  - group: wheels


jobs:


- job: 'JQ'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: sudo apt-get install -y jq
    displayName: 'Install JQ'
  - bash: |
      shopt -s globstar
      cat **/*.json | jq '.'
    displayName: 'Run JQ'
