# https://dev.azure.com/home-assistant

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - components/*
pr: none
schedules:
- cron: '0 */8 * * *'
  displayName: 'daily builds'
  branches:
    include:
    - dev
  always: true
variables:
  - name: versionWheels
    value: '1.1-3.7-alpine3.10'
resources:
  repositories:
    - repository: azure
      type: github
      name: 'home-assistant/ci-azure'
      endpoint: 'home-assistant'

jobs:

- template: templates/azp-job-wheels.yaml@azure
  parameters:
    builderVersion: '$(versionWheels)'
    builderApk: 'build-base;cmake;git;linux-headers;bluez-dev;libffi-dev;openssl-dev;glib-dev;eudev-dev;libxml2-dev;libxslt-dev;libpng-dev;libjpeg-turbo-dev;tiff-dev;autoconf;automake;cups-dev;linux-headers;gmp-dev;mpfr-dev;mpc1-dev;ffmpeg-dev'
    wheelsRequirement: 'requirements.txt'
    wheelsSingle: true
    preBuild:
    - script: |
        for component in components/*; do
          manifest="$(jq --raw-output ".manifest" "${component}")"
          curl -s "${manifest}" | jq --raw-output '.requirements | join("\n")' >> requirements.txt
        done
